### ISSUE TITLE
Can not build

### ISSUE THREAD

**Issue by rogeralsing** [bazingatechnologies/Zipkin.Tracer#6]
There seems to be some issue regarding Thrift nuget version.
Doing a clone of the repo and running the build.bat results in a failure that there are a lot of operations missing on `TProtocol`.

Manually fiddling with the thrift nuget have the same effect.

**Comment by Horusiath** [comment]
I think, it maybe a problem with `Thrift` nuget  - official nuget package is called `ApacheThrift`. Could that be a source of an issue?

**Comment by rogeralsing** [comment]
It works now, dont know what I did, some nuget issue of some sort. closing
